### ISSUE TITLE
Rendering `undefined`

### ISSUE THREAD

**Issue by hankandre** [vercel/next-plugins#24]
Following the example repo the app renders briefly and then show up as `undefined`. I've put together an example at: https://glitch.com/edit/#!/bustling-hook

It looks like it could be a problem loading the common.js module.

**Comment by timneutkens** [comment]
This is caused by the commons logic only including react and react-dom in commons.js in development. `preact` is not `react` according to webpack, so there's no common bundle and webpack won't output it because of that. The solution is to wrap the minchunk config in the next-preact module and add the right config.

**Comment by hankandre** [comment]
👍 closing. Thanks @timneutkens!

**Comment by timneutkens** [comment]
I'd still like to fix it 😄

**Comment by johhansantana** [comment]
What would be the exact workaround for this I can't figure out your solution @timneutkens 😞

**Comment by Clebal** [comment]
Any news about this? I'm having this issue with Next.js 7.0.2
