### ISSUE TITLE
Blows up in IE

### ISSUE THREAD

**Issue by txbrown** [vercel/next-plugins#324]
Arrow function on first line is not transpiled to ES5.

Are we doing something wrong or is it expected behaviour?

**Comment by kachkaev** [comment]
Hi @codenakama! Which IE version? Which function?

I recently tested my app based on Next 7.0.2 and it did work in IE 11.

**Comment by codenakama** [comment]
@kachkaev thanks for replying! 

I did upgrade to 7.0.2 and tested again and still get syntax error within IE 11

this how our` next.config.js` looks like
```
const withTypescript = require('@zeit/next-typescript');

const isProduction = process.env.NODE_ENV === 'production';

module.exports = withTypescript({
  assetPrefix: isProduction ? '/apps/portal' : '',

  distDir: 'build',
  webpack: config => config,
  webpackDevMiddleware: config => config,
  exportPathMap: () => ({
    ...
  }),
});
```

**Comment by kachkaev** [comment]
Hmmm... I'm also using typescript in Next 7.0.2 and all is fine in IE 11 (I my case I just had to polyfill I18n with https://polyfill.io/, but that's not related to syntax).

Could you please provide a minimal working example (MWE) with your issue? If there is a shared repo where your bug gets reproduced, it's much easier to figure out where the problem is originating from.

**Comment by codenakama** [comment]
@kachkaev I will provide you with one soon. thanks for helping!
