### ISSUE TITLE
next-typescript: make `.babelrc` unnecessary

### ISSUE THREAD

**Issue by balupton** [vercel/next-plugins#362]
If the user doesn't have a `.babelrc` then it should not be needed, `next-typescript` should add it for us.

**Comment by balupton** [comment]
Can we not close issues without stating why they were closed?

**Comment by timneutkens** [comment]
> This repository has been deprecated in favor of the Next.js monorepo: vercel/next.js

General cleanup of the repository. This issue was created 2 years ago and no comments/👍 or any other communication was added so it looked very stale, the close without comment was actually to prevent you from getting pinged on a solved issue.

This issue has become irrelevant since Next.js has built-in TypeScript support since last year which handles all TypeScript setup automatically. You can read the docs here: https://nextjs.org/docs/basic-features/typescript
