### ISSUE TITLE
Not working css chunks

### ISSUE THREAD

**Issue by kodermax** [vercel/next-plugins#453]
When I use next-css, I only get one css file at the output

**Comment by nisargrthakkar** [comment]
yes getting the same issue

**Comment by pencilcheck** [comment]
same, and it is a big 30mb+ chunk, I would like to know how to resolve this as it is slowing down loading the website significantly

**Comment by pencilcheck** [comment]
Found a hacky way, go to your next.config.js and add the optimization the way it is written here, it will change the chunk behavior, you can change the 'async' back to 'all' if needed.

You can consult the full documentation of the full options here: https://webpack.js.org/plugins/split-chunks-plugin/

This works because the arthur of the next-css is enforcing certain style rules, which is very weird
https://github.com/zeit/next-plugins/blob/master/packages/next-css/css-loader-config.js

```
const resolve = require('resolve')
const path = require("path");
const glob = require("glob");
const withSass = require("@zeit/next-sass");
const withCSS = require('@zeit/next-css');
const withGraphql = require("next-plugin-graphql");

const compose = require('next-compose')

module.exports = compose([
  [withGraphql, {}],
  [withCSS, {}],
  [withSass, {
    sassLoaderOptions: {
      includePaths: [require('path').resolve(__dirname, 'node_modules')]
    }
  }],
  {
    webpack: (config, { buildId, dev, dir, isServer, defaultLoaders }) => {
      // enable production source map
      if (!dev) {
        config.devtool = "source-map";
      }

      // polyfill
      const originalEntry = config.entry;
      config.entry = async () => {
        const entries = await originalEntry();
        if (entries["main.js"]) {
          entries["main.js"].unshift("./client/polyfills.js");
        }
        return entries;
      };

      config.optimization = {
        splitChunks: {
          ...config.optimization.splitChunk,
          chunks: 'async',
          minSize: 10000,
          maxSize: 0,
          minChunks: 2,
          maxAsyncRequests: 5,
          maxInitialRequests: 3,
          automaticNameDelimiter: '~',
          name: true,
          cacheGroups: {
            styles: {
              enforce: false
            }
          }
        }
      }

      return config;
    }
  }
])
```

**Comment by arnaudDerbey** [comment]
I went threw this annoying un-optimization (hopefully I hadn't 30mo of css to serve 😌), and found another hacky way.

 it appear that with the `@next/with-css` plugins has these lines of code which merge all css files: 

`// css-loader-config.js`

`  if (!isServer) {`
`    config.optimization.splitChunks.cacheGroups.styles = {`
`       name: "styles",`
  `     test: new RegExp(`\\.+(${[...fileExtensions].join("|")})$`),`
`       chunks: "async",`
  `     enforce: true`
`    };`
`  }`


Fork the repo and just remove these part. 

But here is the next problem:  loading critical css in order to avoid the ugly flickering. 
For these problem i found two solutions: 

**-** serve the css into a `link` tag from your static folder
`<link rel="stylesheet" href="/static/CSS/[name].css"/>`

**-** serve your page as dynamic component
`// /pages/[name].js`

`const Component =  dynamic(() => import("../components/[name]"));`
`export default Component; `

**-** refactor the styling part (or at least the critical part) with `styled-components` (or another css in js-lib) which I think is generally a good idea and a kind of a SOTA practice.

Refactoring is certainly a long process but in the meantime you can also use a combination of these three method. Hope it help 😇🙏

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
