### ISSUE TITLE
Conflicting order between .scss files

### ISSUE THREAD

**Issue by remjx** [vercel/next-plugins#606]
I am getting this error in the Next console. These are from 2 separate components that do not share any of the same class names. What could be causing this?

```
[ warn ]  chunk styles [mini-css-extract-plugin]
Conflicting order between:
 * css ../node_modules/css-loader??ref--6-2!../node_modules/sass-loader/lib/loader.js??ref--6-3!./src/components/components/SmallFixedBottomRightButton/SmallFixedBottomRightButton
.scss
 * css ../node_modules/css-loader??ref--6-2!../node_modules/sass-loader/lib/loader.js??ref--6-3!./src/components/components/Loading/LoadingBars/LoadingBars.scss
```

**Comment by swieton** [comment]
I just saw this on my project. I think one of the tools can't figure out what order those two CSS files (given CSS' cascading behavior) should go in. I think that's coming from here: https://github.com/webpack-contrib/mini-css-extract-plugin/blob/1ffc393a2e377fe0cc341cfcbc5396e07a8e4077/src/index.js#L506

Since next-css with css modules namespaces the class names, I don't think this is a problem in my case. See [mini-css-extract-plugin.](https://github.com/webpack-contrib/mini-css-extract-plugin#remove-order-warnings)

I think the next-css plugin is using it from [here](https://github.com/zeit/next-plugins/blob/0735096aa72354b79807972132e88d042be8ed14/packages/next-css/css-loader-config.js#L35):  It's not obvious to me how to affect the options that are passed to it.

For now, on my project, I'm just ignoring the output it.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
