### ISSUE TITLE
ModuleParseError: Module parse failed: Unexpected character '' (1:6)

### ISSUE THREAD

**Issue by codyng** [vercel/next-plugins#617]
Hi there,

I have made my own wrapper component for Photoswipe and imported the Photoswipe css inside. Although compilation succeeded, there is the runtime js error:

./node_modules/photoswipe/dist/default-skin/default-skin.css
ModuleParseError: Module parse failed: Unexpected character '' (1:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Is it the internal parsing problem or Photoswipe problem? while it is fine to embed other library css.
Thanks.

**Comment by phenax** [comment]
+1

**Comment by Baira** [comment]
Hello,

It would have been better if you could include snippets of your `next.config.json`. Anyway I'll try to give you some leads :

You might be only using `next-css` for importing your plugin css files. The problem is that the css file could be also importing images, fonts, etc. You will need additional plugins for that. 

Let's assume that your `next.config.json` resembles something like this : 

```javascript
const nextConfig = {
  trailingSlash: false,
  poweredByHeader: false,
  webpack(config, options) {
    const { isServer } = options;
    config.resolve.alias = {
      ...config.resolve.alias,
      '@components': path.resolve('./components'),
      '@public': path.resolve('./public'),
      '@redux': path.resolve('./redux'),
      '@utils': path.resolve('./utils'),
    };

    return config;
  },
};

module.exports = withPlugins(
  [withCSS],
  nextConfig,
);
```
If your css uses images and fonts you will need this :
```javascript
const nextConfig = {
  trailingSlash: false,
  poweredByHeader: false,
  webpack(config, options) {
    const { isServer } = options;
    config.resolve.alias = {
      ...config.resolve.alias,
      '@components': path.resolve('./components'),
      '@public': path.resolve('./public'),
      '@redux': path.resolve('./redux'),
      '@utils': path.resolve('./utils'),
    };

    config.module.rules.push({
      test: /\.(woff|woff2|eot|ttf|otf)$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[name]-[hash:8].[ext]',
            publicPath: (url) => {
              return `/_next/static/css/${url}`;
            },
            outputPath: `${isServer ? '../' : ''}static/css/`,
            esModule: false,
          },
        },
      ],
    });

    return config;
  },
};

module.exports = withPlugins(
  [withCSS],
  withImages,
  nextConfig,
);
```
The error thrown by nextjs unfortunately isn't specific. If for example instead of next-css you used webpack's style-loader and css-loader in module.rules, webpack will precisely tell you that he doesn't have a loader for the specific file it encountered while parsing the css file.

Good luck.

**Comment by nybik1** [comment]
Ya dibil

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
