### ISSUE TITLE
with-less will disable build in css-loader

### ISSUE THREAD

**Issue by swaitw** [vercel/next-plugins#672]
when use use-less, the build-in css loader will be disabled, current solution is i have to use  with-css, is it possible i can use with-less without disable the build-in css-loader due to the with-css plugin is look like not supported  anymore( no update).
thanks!

**Comment by swaitw** [comment]
also,I hope there should be some instruction in the document to tell users is there any side effects if we use with-css instead of  build-in css loader. currently there is noting  about difference between build-css loader and with-css. thanks a lot.

**Comment by llamadeus** [comment]
The main difference is, that the built-in version of css-loader is v4.3.0 while `@zeit/next-less v1.0.1` uses `@zeit/next-css v1.0.1` which uses `css-loader v1.0.0` which is basically not usable anymore.

I'm currently having the same problem with the `next-less` package. I want to use less modules but due to this issue I cannot specify the correct css-loader options.

Actually the [readme.md](https://github.com/vercel/next-plugins/blob/%40zeit/next-less%401.0.1/packages/next-less/readme.md) of `next-less` file refers to the `css-loader` options documentation on the master branch while under the hood v1.0.0 is being used.
