### ISSUE TITLE
next-workers not working in Next 10?

### ISSUE THREAD

**Issue by ezekielaquino** [vercel/next-plugins#682]
followed the documentation, but whatever I do, the loader does not seem to work

**Comment by isaiasneto** [comment]
I've tried and nothing to...

**Comment by ezekielaquino** [comment]
What finally worked for me was to use [comlink](https://github.com/GoogleChromeLabs/comlink) which imo has a nicer api. Still would've been nice to have an official next plugin that works as nice as next.js itself :-)

**Comment by SelimAbidin** [comment]
I came to open an Issue/PR but ended here. 

The problem is next-workers uses worker-loader@2.0.0 which uses an schema like object {name: string, ...rest} but when you use +2 version (because you followed Readme), you will install something like worker-loader@3.0 which uses schema object {filename: string ...rest }.

Check your worker-loader version and if you see newer version than 2.0, you may want to use this in your next.config.js
 

const withWorkers = require('@zeit/next-workers')

```
module.exports = withWorkers({
    workerLoaderOptions: {
        filename: 'static/[hash].worker.js',
        publicPath: '/_next/',
    }
})
```

or you can just install the correct version that next-workers uses
```
yarn add @zeit/next-workers worker-loader@^2.0.0
```
worker-loader may warn you about webpack unmeet libraries but it will still work. I recommend editing config.



I would like to contribute with a PR but I am not sure if I should update the readme or the code since both works. 
Any guide?
